[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32"

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c6"

[env]
ESP_LOG="info"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32-none-elf"
#target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
